class CreateReportDataCountries < ActiveRecord::Migration
  def up
    create_table :report_data_countries do |t|
      t.string :name
      t.string :code_iso
      t.string :code_un

      t.timestamps
    end

    # # Populate the countries!
    ReportDataCountry.create!([
      { name: "Afghanistan", code_iso: "AF", code_un: "AFG" },
      { name: "Albania", code_iso: "AL", code_un: "ALB" },
      { name: "Algeria", code_iso: "DZ", code_un: "DZA" },
      { name: "American Samoa", code_iso: "AS", code_un: "ASM" },
      { name: "Andorra", code_iso: "AD", code_un: "AND" },
      { name: "Angola", code_iso: "AO", code_un: "AGO" },
      { name: "Anguilla", code_iso: "AI", code_un: "AIA" },
      { name: "Antarctica", code_iso: "AQ", code_un: "ATA" },
      { name: "Antigua and Barbuda", code_iso: "AG", code_un: "ATG" },
      { name: "Argentina", code_iso: "AR", code_un: "ARG" },
      { name: "Armenia", code_iso: "AM", code_un: "ARM" },
      { name: "Aruba", code_iso: "AW", code_un: "ABW" },
      { name: "Australia", code_iso: "AU", code_un: "AUS" },
      { name: "Austria", code_iso: "AT", code_un: "AUT" },
      { name: "Azerbaijan", code_iso: "AZ", code_un: "AZE" },
      { name: "Bahamas", code_iso: "BS", code_un: "BHS" },
      { name: "Bahrain", code_iso: "BH", code_un: "BHR" },
      { name: "Bangladesh", code_iso: "BD", code_un: "BGD" },
      { name: "Barbados", code_iso: "BB", code_un: "BRB" },
      { name: "Belarus", code_iso: "BY", code_un: "BLR" },
      { name: "Belgium", code_iso: "BE", code_un: "BEL" },
      { name: "Belize", code_iso: "BZ", code_un: "BLZ" },
      { name: "Benin", code_iso: "BJ", code_un: "BEN" },
      { name: "Bermuda", code_iso: "BM", code_un: "BMU" },
      { name: "Bhutan", code_iso: "BT", code_un: "BTN" },
      { name: "Bolivia", code_iso: "BO", code_un: "BOL" },
      { name: "Bonaire", code_iso: "BQ", code_un: "BES" },
      { name: "Bosnia and Herzegovina", code_iso: "BA", code_un: "BIH" },
      { name: "Botswana", code_iso: "BW", code_un: "BWA" },
      { name: "Bouvet Island", code_iso: "BV", code_un: "BVT" },
      { name: "Brazil", code_iso: "BR", code_un: "BRA" },
      { name: "British Indian Ocean Territory", code_iso: "IO", code_un: "IOT" },
      { name: "Brunei Darussalam", code_iso: "BN", code_un: "BRN" },
      { name: "Bulgaria", code_iso: "BG", code_un: "BGR" },
      { name: "Burkina Faso", code_iso: "BF", code_un: "BFA" },
      { name: "Burundi", code_iso: "BI", code_un: "BDI" },
      { name: "Cambodia", code_iso: "KH", code_un: "KHM" },
      { name: "Cameroon", code_iso: "CM", code_un: "CMR" },
      { name: "Canada", code_iso: "CA", code_un: "CAN" },
      { name: "Cape Verde", code_iso: "CV", code_un: "CPV" },
      { name: "Cayman Islands", code_iso: "KY", code_un: "CYM" },
      { name: "Central African Republic", code_iso: "CF", code_un: "CAF" },
      { name: "Chad", code_iso: "TD", code_un: "TCD" },
      { name: "Chile", code_iso: "CL", code_un: "CHL" },
      { name: "China", code_iso: "CN", code_un: "CHN" },
      { name: "Christmas Island", code_iso: "CX", code_un: "CXR" },
      { name: "Cocos (Keeling) Islands", code_iso: "CC", code_un: "CCK" },
      { name: "Colombia", code_iso: "CO", code_un: "COL" },
      { name: "Comoros", code_iso: "KM", code_un: "COM" },
      { name: "Congo", code_iso: "CG", code_un: "COG" },
      { name: "Democratic Republic of the Congo", code_iso: "CD", code_un: "COD" },
      { name: "Cook Islands", code_iso: "CK", code_un: "COK" },
      { name: "Costa Rica", code_iso: "CR", code_un: "CRI" },
      { name: "Croatia", code_iso: "HR", code_un: "HRV" },
      { name: "Cuba", code_iso: "CU", code_un: "CUB" },
      { name: "CuraÃ§ao", code_iso: "CW", code_un: "CUW" },
      { name: "Cyprus", code_iso: "CY", code_un: "CYP" },
      { name: "Czech Republic", code_iso: "CZ", code_un: "CZE" },
      { name: "CÃ´te d'Ivoire", code_iso: "CI", code_un: "CIV" },
      { name: "Denmark", code_iso: "DK", code_un: "DNK" },
      { name: "Djibouti", code_iso: "DJ", code_un: "DJI" },
      { name: "Dominica", code_iso: "DM", code_un: "DMA" },
      { name: "Dominican Republic", code_iso: "DO", code_un: "DOM" },
      { name: "Ecuador", code_iso: "EC", code_un: "ECU" },
      { name: "Egypt", code_iso: "EG", code_un: "EGY" },
      { name: "El Salvador", code_iso: "SV", code_un: "SLV" },
      { name: "Equatorial Guinea", code_iso: "GQ", code_un: "GNQ" },
      { name: "Eritrea", code_iso: "ER", code_un: "ERI" },
      { name: "Estonia", code_iso: "EE", code_un: "EST" },
      { name: "Ethiopia", code_iso: "ET", code_un: "ETH" },
      { name: "Falkland Islands (Malvinas)", code_iso: "FK", code_un: "FLK" },
      { name: "Faroe Islands", code_iso: "FO", code_un: "FRO" },
      { name: "Fiji", code_iso: "FJ", code_un: "FJI" },
      { name: "Finland", code_iso: "FI", code_un: "FIN" },
      { name: "France", code_iso: "FR", code_un: "FRA" },
      { name: "French Guiana", code_iso: "GF", code_un: "GUF" },
      { name: "French Polynesia", code_iso: "PF", code_un: "PYF" },
      { name: "French Southern Territories", code_iso: "TF", code_un: "ATF" },
      { name: "Gabon", code_iso: "GA", code_un: "GAB" },
      { name: "Gambia", code_iso: "GM", code_un: "GMB" },
      { name: "Georgia", code_iso: "GE", code_un: "GEO" },
      { name: "Germany", code_iso: "DE", code_un: "DEU" },
      { name: "Ghana", code_iso: "GH", code_un: "GHA" },
      { name: "Gibraltar", code_iso: "GI", code_un: "GIB" },
      { name: "Greece", code_iso: "GR", code_un: "GRC" },
      { name: "Greenland", code_iso: "GL", code_un: "GRL" },
      { name: "Grenada", code_iso: "GD", code_un: "GRD" },
      { name: "Guadeloupe", code_iso: "GP", code_un: "GLP" },
      { name: "Guam", code_iso: "GU", code_un: "GUM" },
      { name: "Guatemala", code_iso: "GT", code_un: "GTM" },
      { name: "Guernsey", code_iso: "GG", code_un: "GGY" },
      { name: "Guinea", code_iso: "GN", code_un: "GIN" },
      { name: "Guinea-Bissau", code_iso: "GW", code_un: "GNB" },
      { name: "Guyana", code_iso: "GY", code_un: "GUY" },
      { name: "Haiti", code_iso: "HT", code_un: "HTI" },
      { name: "Heard Island and McDonald Mcdonald Islands", code_iso: "HM", code_un: "HMD" },
      { name: "Holy See (Vatican City State)", code_iso: "VA", code_un: "VAT" },
      { name: "Honduras", code_iso: "HN", code_un: "HND" },
      { name: "Hong Kong", code_iso: "HK", code_un: "HKG" },
      { name: "Hungary", code_iso: "HU", code_un: "HUN" },
      { name: "Iceland", code_iso: "IS", code_un: "ISL" },
      { name: "India", code_iso: "IN", code_un: "IND" },
      { name: "Indonesia", code_iso: "ID", code_un: "IDN" },
      { name: "Iran, Islamic Republic of", code_iso: "IR", code_un: "IRN" },
      { name: "Iraq", code_iso: "IQ", code_un: "IRQ" },
      { name: "Ireland", code_iso: "IE", code_un: "IRL" },
      { name: "Isle of Man", code_iso: "IM", code_un: "IMN" },
      { name: "Israel", code_iso: "IL", code_un: "ISR" },
      { name: "Italy", code_iso: "IT", code_un: "ITA" },
      { name: "Jamaica", code_iso: "JM", code_un: "JAM" },
      { name: "Japan", code_iso: "JP", code_un: "JPN" },
      { name: "Jersey", code_iso: "JE", code_un: "JEY" },
      { name: "Jordan", code_iso: "JO", code_un: "JOR" },
      { name: "Kazakhstan", code_iso: "KZ", code_un: "KAZ" },
      { name: "Kenya", code_iso: "KE", code_un: "KEN" },
      { name: "Kiribati", code_iso: "KI", code_un: "KIR" },
      { name: "Korea, Democratic People's Republic of", code_iso: "KP", code_un: "PRK" },
      { name: "Korea, Republic of", code_iso: "KR", code_un: "KOR" },
      { name: "Kuwait", code_iso: "KW", code_un: "KWT" },
      { name: "Kyrgyzstan", code_iso: "KG", code_un: "KGZ" },
      { name: "Lao People's Democratic Republic", code_iso: "LA", code_un: "LAO" },
      { name: "Latvia", code_iso: "LV", code_un: "LVA" },
      { name: "Lebanon", code_iso: "LB", code_un: "LBN" },
      { name: "Lesotho", code_iso: "LS", code_un: "LSO" },
      { name: "Liberia", code_iso: "LR", code_un: "LBR" },
      { name: "Libya", code_iso: "LY", code_un: "LBY" },
      { name: "Liechtenstein", code_iso: "LI", code_un: "LIE" },
      { name: "Lithuania", code_iso: "LT", code_un: "LTU" },
      { name: "Luxembourg", code_iso: "LU", code_un: "LUX" },
      { name: "Macao", code_iso: "MO", code_un: "MAC" },
      { name: "Macedonia, the Former Yugoslav Republic of", code_iso: "MK", code_un: "MKD" },
      { name: "Madagascar", code_iso: "MG", code_un: "MDG" },
      { name: "Malawi", code_iso: "MW", code_un: "MWI" },
      { name: "Malaysia", code_iso: "MY", code_un: "MYS" },
      { name: "Maldives", code_iso: "MV", code_un: "MDV" },
      { name: "Mali", code_iso: "ML", code_un: "MLI" },
      { name: "Malta", code_iso: "MT", code_un: "MLT" },
      { name: "Marshall Islands", code_iso: "MH", code_un: "MHL" },
      { name: "Martinique", code_iso: "MQ", code_un: "MTQ" },
      { name: "Mauritania", code_iso: "MR", code_un: "MRT" },
      { name: "Mauritius", code_iso: "MU", code_un: "MUS" },
      { name: "Mayotte", code_iso: "YT", code_un: "MYT" },
      { name: "Mexico", code_iso: "MX", code_un: "MEX" },
      { name: "Micronesia, Federated States of", code_iso: "FM", code_un: "FSM" },
      { name: "Moldova, Republic of", code_iso: "MD", code_un: "MDA" },
      { name: "Monaco", code_iso: "MC", code_un: "MCO" },
      { name: "Mongolia", code_iso: "MN", code_un: "MNG" },
      { name: "Montenegro", code_iso: "ME", code_un: "MNE" },
      { name: "Montserrat", code_iso: "MS", code_un: "MSR" },
      { name: "Morocco", code_iso: "MA", code_un: "MAR" },
      { name: "Mozambique", code_iso: "MZ", code_un: "MOZ" },
      { name: "Myanmar", code_iso: "MM", code_un: "MMR" },
      { name: "Namibia", code_iso: "NA", code_un: "NAM" },
      { name: "Nauru", code_iso: "NR", code_un: "NRU" },
      { name: "Nepal", code_iso: "NP", code_un: "NPL" },
      { name: "Netherlands", code_iso: "NL", code_un: "NLD" },
      { name: "New Caledonia", code_iso: "NC", code_un: "NCL" },
      { name: "New Zealand", code_iso: "NZ", code_un: "NZL" },
      { name: "Nicaragua", code_iso: "NI", code_un: "NIC" },
      { name: "Niger", code_iso: "NE", code_un: "NER" },
      { name: "Nigeria", code_iso: "NG", code_un: "NGA" },
      { name: "Niue", code_iso: "NU", code_un: "NIU" },
      { name: "Norfolk Island", code_iso: "NF", code_un: "NFK" },
      { name: "Northern Mariana Islands", code_iso: "MP", code_un: "MNP" },
      { name: "Norway", code_iso: "NO", code_un: "NOR" },
      { name: "Oman", code_iso: "OM", code_un: "OMN" },
      { name: "Pakistan", code_iso: "PK", code_un: "PAK" },
      { name: "Palau", code_iso: "PW", code_un: "PLW" },
      { name: "Palestine, State of", code_iso: "PS", code_un: "PSE" },
      { name: "Panama", code_iso: "PA", code_un: "PAN" },
      { name: "Papua New Guinea", code_iso: "PG", code_un: "PNG" },
      { name: "Paraguay", code_iso: "PY", code_un: "PRY" },
      { name: "Peru", code_iso: "PE", code_un: "PER" },
      { name: "Philippines", code_iso: "PH", code_un: "PHL" },
      { name: "Pitcairn", code_iso: "PN", code_un: "PCN" },
      { name: "Poland", code_iso: "PL", code_un: "POL" },
      { name: "Portugal", code_iso: "PT", code_un: "PRT" },
      { name: "Puerto Rico", code_iso: "PR", code_un: "PRI" },
      { name: "Qatar", code_iso: "QA", code_un: "QAT" },
      { name: "Romania", code_iso: "RO", code_un: "ROU" },
      { name: "Russian Federation", code_iso: "RU", code_un: "RUS" },
      { name: "Rwanda", code_iso: "RW", code_un: "RWA" },
      { name: "Reunion", code_iso: "RE", code_un: "REU" },
      { name: "Saint Barthalemy", code_iso: "BL", code_un: "BLM" },
      { name: "Saint Helena", code_iso: "SH", code_un: "SHN" },
      { name: "Saint Kitts and Nevis", code_iso: "KN", code_un: "KNA" },
      { name: "Saint Lucia", code_iso: "LC", code_un: "LCA" },
      { name: "Saint Martin (French part)", code_iso: "MF", code_un: "MAF" },
      { name: "Saint Pierre and Miquelon", code_iso: "PM", code_un: "SPM" },
      { name: "Saint Vincent and the Grenadines", code_iso: "VC", code_un: "VCT" },
      { name: "Samoa", code_iso: "WS", code_un: "WSM" },
      { name: "San Marino", code_iso: "SM", code_un: "SMR" },
      { name: "Sao Tome and Principe", code_iso: "ST", code_un: "STP" },
      { name: "Saudi Arabia", code_iso: "SA", code_un: "SAU" },
      { name: "Senegal", code_iso: "SN", code_un: "SEN" },
      { name: "Serbia", code_iso: "RS", code_un: "SRB" },
      { name: "Seychelles", code_iso: "SC", code_un: "SYC" },
      { name: "Sierra Leone", code_iso: "SL", code_un: "SLE" },
      { name: "Singapore", code_iso: "SG", code_un: "SGP" },
      { name: "Sint Maarten (Dutch part)", code_iso: "SX", code_un: "SXM" },
      { name: "Slovakia", code_iso: "SK", code_un: "SVK" },
      { name: "Slovenia", code_iso: "SI", code_un: "SVN" },
      { name: "Solomon Islands", code_iso: "SB", code_un: "SLB" },
      { name: "Somalia", code_iso: "SO", code_un: "SOM" },
      { name: "South Africa", code_iso: "ZA", code_un: "ZAF" },
      { name: "South Georgia and the South Sandwich Islands", code_iso: "GS", code_un: "SGS" },
      { name: "South Sudan", code_iso: "SS", code_un: "SSD" },
      { name: "Spain", code_iso: "ES", code_un: "ESP" },
      { name: "Sri Lanka", code_iso: "LK", code_un: "LKA" },
      { name: "Sudan", code_iso: "SD", code_un: "SDN" },
      { name: "Suriname", code_iso: "SR", code_un: "SUR" },
      { name: "Svalbard and Jan Mayen", code_iso: "SJ", code_un: "SJM" },
      { name: "Swaziland", code_iso: "SZ", code_un: "SWZ" },
      { name: "Sweden", code_iso: "SE", code_un: "SWE" },
      { name: "Switzerland", code_iso: "CH", code_un: "CHE" },
      { name: "Syrian Arab Republic", code_iso: "SY", code_un: "SYR" },
      { name: "Taiwan, Province of China", code_iso: "TW", code_un: "TWN" },
      { name: "Tajikistan", code_iso: "TJ", code_un: "TJK" },
      { name: "United Republic of Tanzania", code_iso: "TZ", code_un: "TZA" },
      { name: "Thailand", code_iso: "TH", code_un: "THA" },
      { name: "Timor-Leste", code_iso: "TL", code_un: "TLS" },
      { name: "Togo", code_iso: "TG", code_un: "TGO" },
      { name: "Tokelau", code_iso: "TK", code_un: "TKL" },
      { name: "Tonga", code_iso: "TO", code_un: "TON" },
      { name: "Trinidad and Tobago", code_iso: "TT", code_un: "TTO" },
      { name: "Tunisia", code_iso: "TN", code_un: "TUN" },
      { name: "Turkey", code_iso: "TR", code_un: "TUR" },
      { name: "Turkmenistan", code_iso: "TM", code_un: "TKM" },
      { name: "Turks and Caicos Islands", code_iso: "TC", code_un: "TCA" },
      { name: "Tuvalu", code_iso: "TV", code_un: "TUV" },
      { name: "Uganda", code_iso: "UG", code_un: "UGA" },
      { name: "Ukraine", code_iso: "UA", code_un: "UKR" },
      { name: "United Arab Emirates", code_iso: "AE", code_un: "ARE" },
      { name: "United Kingdom", code_iso: "GB", code_un: "GBR" },
      { name: "United States", code_iso: "US", code_un: "USA" },
      { name: "United States Minor Outlying Islands", code_iso: "UM", code_un: "UMI" },
      { name: "Uruguay", code_iso: "UY", code_un: "URY" },
      { name: "Uzbekistan", code_iso: "UZ", code_un: "UZB" },
      { name: "Vanuatu", code_iso: "VU", code_un: "VUT" },
      { name: "Venezuela", code_iso: "VE", code_un: "VEN" },
      { name: "Viet Nam", code_iso: "VN", code_un: "VNM" },
      { name: "British Virgin Islands", code_iso: "VG", code_un: "VGB" },
      { name: "US Virgin Islands", code_iso: "VI", code_un: "VIR" },
      { name: "Wallis and Futuna", code_iso: "WF", code_un: "WLF" },
      { name: "Western Sahara", code_iso: "EH", code_un: "ESH" },
      { name: "Yemen", code_iso: "YE", code_un: "YEM" },
      { name: "Zambia", code_iso: "ZM", code_un: "ZMB" },
      { name: "Zimbabwe", code_iso: "ZW", code_un: "ZWE" },
      { name: "Aland Islands", code_iso: "AX", code_un: "ALA" },
    ])

  end

  def down
    drop_table :report_data_countries
  end

end
